### ISSUE TITLE
[Task 10] Garantir que o player e a moeda spawnem em lugares validos

### ISSUE THREAD

**Issue by Feggah** [arthurghz/Intelig-ncia_Artificial_Godot#18]

**Comment by HeavyBR** [comment]
Estou com essa task galerda

**Comment by Feggah** [comment]
Acho que nessa task vai precisar adicionar botoes pra respawn do player e da moeda, caso eles nasçam presos... se isso acontecer, é importante atualizar os valores nas variaveis (tipo se a moeda 2 for respawnada, acho que vai ter que mudar o valor da posicao 2 do vetor das moedas, e chamar o A* dnv - ja que ele vai calcular os paths logo que a moeda for criada - ) pra nao bugar o A*

**Comment by Feggah** [comment]
Ou se o player nascer em uma posicao bugada (que a chance é muito muito baixa) fazer um botao de restart phase, algo do tipo, pq senao vai ser uma chatisse ficar atualizando a posicao do player pro A*
