### ISSUE TITLE
[Task 5] Desenvolver algoritmo A*

### ISSUE THREAD

**Issue by Feggah** [arthurghz/Intelig-ncia_Artificial_Godot#7]

**Comment by HeavyBR** [comment]
**Talvez possa ajudar:**

- [ ] Assistir [esse vídeo](https://www.youtube.com/watch?v=Ad6Us73smNs)

- [ ] Dar uma olhada [nessa classe](https://docs.godotengine.org/en/3.1/classes/class_astar.html)

**Comment by Feggah** [comment]
Opa, beleza, vi aqui @HeavyBR 

Também achei interessante dois vídeos pra assistir, ele codifica em javascript o A*, é um vídeo separado em duas partes

- [ ] [Parte 1](https://www.youtube.com/watch?v=aKYlikFAV4k)
- [ ] [Parte 2](https://www.youtube.com/watch?v=EaZxUCWAjb0)
